[package]
name = "rhof-web"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
rhof-core = { path = "../rhof-core" }
rhof-storage = { path = "../rhof-storage" }
